---
- name: Manage APT
  tags: apt
  become: true
  block:
    - name: Install python3-debian
      apt:
        name: python3-debian
    - name: Manage sources
      deb822_repository:
        name: "{{ item.name }}"
        types: "{{ item.types | default(omit) }}"
        uris: "{{ item.uris }}"
        suites: "{{ item.suites }}"
        components: "{{ item.components }}"
        signed_by: "{{ item.signed_by | default(omit) }}"
      with_items: "{{ apt_sources }}"
      notify: Update package cache
